name: shared
version: 1.0.0+1
publish_to: none
description: Shared Packages.
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: "2.10.2"

dependencies:
  data:
    path: ../data
  text_to_multi_transleting:
    path: ../../
  flutter_tts: ^3.3.3

  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

